package com.alancamargo.tweetreader.ui.di

const val UI_EXTENDED_TWEET_MAPPER = "UI_EXTENDED_TWEET_MAPPER"
const val UI_MEDIA_CONTENT_MAPPER = "UI_MEDIA_CONTENT_MAPPER"
const val UI_MEDIA_MAPPER = "UI_MEDIA_MAPPER"
const val UI_TWEET_MAPPER = "UI_TWEET_MAPPER"
const val UI_USER_MAPPER = "UI_USER_MAPPER"
const val UI_VIDEO_INFO_MAPPER = "UI_VIDEO_INFO_MAPPER"
const val UI_VIDEO_VARIANT_MAPPER = "UI_VIDEO_VARIANT_MAPPER"