package com.alancamargo.tweetreader.framework.di

const val EXTENDED_TWEET_RESPONSE_MAPPER = "EXTENDED_TWEET_RESPONSE_MAPPER"
const val MEDIA_CONTENT_RESPONSE_MAPPER = "MEDIA_CONTENT_RESPONSE_MAPPER"
const val MEDIA_RESPONSE_MAPPER = "MEDIA_RESPONSE_MAPPER"
const val TWEET_RESPONSE_MAPPER = "TWEET_RESPONSE_MAPPER"
const val USER_RESPONSE_MAPPER = "USER_RESPONSE_MAPPER"
const val VIDEO_INFO_RESPONSE_MAPPER = "VIDEO_INFO_RESPONSE_MAPPER"
const val VIDEO_VARIANT_RESPONSE_MAPPER = "VIDEO_VARIANT_RESPONSE_MAPPER"

const val EXTENDED_TWEET_MAPPER = "EXTENDED_TWEET_MAPPER"
const val MEDIA_CONTENT_MAPPER = "MEDIA_CONTENT_MAPPER"
const val MEDIA_MAPPER = "MEDIA_MAPPER"
const val TWEET_MAPPER = "TWEET_MAPPER"
const val USER_MAPPER = "USER_MAPPER"
const val VIDEO_INFO_MAPPER = "VIDEO_INFO_MAPPER"
const val VIDEO_VARIANT_MAPPER = "VIDEO_VARIANT_MAPPER"